#ifndef LDG_CORE_ERR_H
#define LDG_CORE_ERR_H

#define LDG_ERR_OK 0
#define LDG_ERR_FUNC_ARG_NULL -1
#define LDG_ERR_FUNC_ARG_INVALID -2
#define LDG_ERR_ALLOC_NULL -3
#define LDG_ERR_NOT_INIT -4
#define LDG_ERR_FULL -5
#define LDG_ERR_OVERFLOW -6
#define LDG_ERR_FILE_NOT_FOUND -7
#define LDG_ERR_FILE_READ -8
#define LDG_ERR_FILE_WRITE -9
#define LDG_ERR_FILE_FORMAT -10
#define LDG_ERR_EMPTY -11
#define LDG_ERR_BUSY -12
#define LDG_ERR_INVALID -13
#define LDG_ERR_TIMEOUT -14

#define LDG_ERR_MEM_BAD -100
#define LDG_ERR_MEM_STR_TRUNC -101
#define LDG_ERR_MEM_MEMMOVE_ALLOCD -102
#define LDG_ERR_MEM_SENTINEL -103
#define LDG_ERR_MEM_POOL_FULL -104
#define LDG_ERR_MEM_POOL_INVALID -105

#define LDG_ERR_TIME_CORE_MIGRATED -200
#define LDG_ERR_TIME_NOT_CALIBRATED -201

#define LDG_ERR_NET_INIT -300
#define LDG_ERR_NET_PERFORM -301
#define LDG_ERR_NET_TIMEOUT -302
#define LDG_ERR_NET_CONN -303

#define LDG_ERR_STR_TRUNC -400
#define LDG_ERR_STR_OVERLAP -401

#endif
