#include <dangling/fmt/fmt.h>

static const char g_uncrustify_cfg[] =
    "indent_with_tabs = 0\n"
    "indent_columns = 4\n"
    "indent_switch_case = 4\n"
    "nl_if_brace = force\n"
    "nl_brace_else = force\n"
    "nl_elseif_brace = force\n"
    "nl_else_brace = force\n"
    "nl_else_if = remove\n"
    "nl_for_brace = force\n"
    "nl_while_brace = force\n"
    "nl_do_brace = force\n"
    "nl_switch_brace = force\n"
    "nl_fdef_brace = force\n"
    "nl_func_type_name = remove\n"
    "nl_enum_brace = force\n"
    "nl_struct_brace = force\n"
    "nl_union_brace = force\n"
    "nl_if_leave_one_liners = true\n"
    "nl_while_leave_one_liners = true\n"
    "nl_for_leave_one_liners = true\n"
    "nl_do_leave_one_liners = true\n"
    "nl_create_if_one_liner = true\n"
    "nl_create_for_one_liner = true\n"
    "nl_create_while_one_liner = true\n"
    "sp_after_ptr_star = remove\n"
    "sp_after_ptr_star_func = force\n"
    "sp_before_ptr_star = force\n"
    "sp_before_ptr_star_func = remove\n"
    "sp_between_ptr_star = remove\n"
    "sp_assign = force\n"
    "sp_arith = force\n"
    "sp_bool = force\n"
    "sp_compare = force\n"
    "sp_after_comma = force\n"
    "sp_before_comma = remove\n"
    "sp_after_cast = remove\n"
    "sp_inside_paren = remove\n"
    "sp_inside_square = remove\n"
    "sp_before_sparen = force\n"
    "sp_inside_sparen = remove\n"
    "mod_full_brace_if = ignore\n"
    "mod_full_brace_for = ignore\n"
    "mod_full_brace_while = ignore\n"
    "mod_full_brace_do = ignore\n"
    "nl_multi_line_cond = false\n"
    "nl_after_if = force\n"
    "nl_after_brace_close = true\n"
    "nl_after_func_body = 2\n"
    "nl_after_func_body_class = 2\n"
    "nl_after_func_body_one_liner = 2\n"
    "nl_after_semicolon = true\n"
    "nl_after_case = true\n"
    "eat_blanks_after_open_brace = false\n"
    "eat_blanks_before_close_brace = false\n"
    "cmt_indent_multi = false\n"
    "code_width = 0\n"
    "ls_code_width = false\n"
    "ls_func_split_full = false\n"
    "ls_for_split_full = false\n"
    "indent_func_call_param = false\n"
    "indent_align_paren = false\n"
    "indent_paren_nl = false\n"
    "align_func_params = false\n"
    "indent_continue = 4\n"
    "use_indent_continue_only_once = true\n"
    "nl_end_of_file = force\n"
    "nl_end_of_file_min = 1\n"
    "nl_func_call_start_multi_line = false\n"
    "nl_func_call_args_multi_line = false\n"
    "nl_func_call_end_multi_line = false\n"
    "nl_func_call_paren = remove\n"
    "nl_func_call_paren_empty = remove\n"
    "nl_func_call_start = remove\n"
    "nl_func_call_end = remove\n"
    "sp_func_call_paren = remove\n"
    "sp_func_proto_paren = remove\n"
    "sp_func_def_paren = remove\n"
    "sp_after_semi_for = force\n"
    "sp_after_semi_for_empty = remove\n"
    "sp_macro = ignore\n"
    "sp_macro_func = ignore\n"
    "sp_member = remove\n"
    "sp_deref = remove\n"
    "sp_addr = remove\n"
    "align_keep_tabs = false\n"
    "align_with_tabs = false\n"
    "align_on_tabstop = false\n"
    "align_var_def_star_style = 2\n"
    "align_var_def_amp_style = 2\n"
    "sp_inside_braces = force\n"
    "sp_inside_braces_struct = force\n"
    "sp_inside_braces_empty = remove\n"
    "sp_brace_typedef = force\n"
    "cmt_sp_after_star_cont = 1\n"
    "pp_indent = remove\n"
    "pp_indent_at_level = false\n"
    "pp_define_at_level = false\n"
    "nl_func_call_args = remove\n"
    "nl_func_def_args = remove\n"
    "nl_func_decl_args = remove\n"
    "pos_comma = join\n"
    "pos_bool = join\n"
    "pos_compare = join\n"
    "pos_conditional = join\n";

const char* ldg_fmt_cfg_get(void)
{
    return g_uncrustify_cfg;
}

const char* ldg_fmt_cfg_path_get(void)
{
    return LDG_FMT_CFG_PATH;
}
